DROP DATABASE IF EXISTS `api-partiel`;

CREATE DATABASE `api-partiel` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE analytics(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    report INTEGER UNIQUE NOT NULL REFERENCES reports(id),
    name VARCHAR(50) NOT NULL,
    value VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE applications(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE reports(   
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    reporter INTEGER UNIQUE NOT NULL REFERENCES users(id),
    application INTEGER UNIQUE NOT NULL REFERENCES applications(id),
    name VARCHAR(50) NOT NULL,
    description TEXT
) ENGINE=InnoDB;

CREATE TABLE users(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL,
    password CHAR(60) NOT NULL,
    token CHAR(32),
    role VARCHAR(20)
) ENGINE=InnoDB;
